### ISSUE TITLE
The scroll bar doesn't stay at the bottom of the div 

### ISSUE THREAD

**Issue by ajsevillano** [ajsevillano/WebsocketChat#7]
I couldn't find yet the way to make the scroll bar to stay at the bottom of the chat window.

**Comment by Apol0x** [comment]
How can I run the project and reproduce the issue?
I thought you were using `npm` and I tryed to install it...
If I can help on something here you are a mate ;)

**Comment by ajsevillano** [comment]
Hi @Apol0x thank you for your comment!
This is a quite simple project just for fun and learning the use of socket.io, I haven't created a npm package yet :)
The best way to put to work the chat is just downloading o clone the repository.
Then, install the dependencies (express and socket.io) (npm install express) and (npm install socket.io).
Then you can start the app with "node index.js"
The issue is in Chrome, when the people start to write, it will reach a point where a scroll bar will appear but it never goes to the botton of the div, so you can't read the new messages.

Thank you again for you offering! Feel free to play around with this project
Best wishes

**Comment by ajsevillano** [comment]
I just realised that you probably will need to change "let socket = io.connect('http://192.168.1.223:4000');" inside chat.js for let socket = io.connect('http://localhost:4000');

**Comment by Apol0x** [comment]
Well testing the project something, you could put this lines when you send new messages 
You have this
```
socket.on('chat', (data) => {
	output.innerHTML += `<p><strong>${data.name}</strong> ${data.message}</p>`;
});
```

And you could try with this
```
socket.on('chat', (data) => {
        let chatContainer =  document.querySelector("#chat-window");
	output.innerHTML += `<p><strong>${data.name}</strong> ${data.message}</p>`;
        chatContainer.scrollTop = chatContainer.scrollHeight;
});
```
Roughly, I hope it will be useful hehehe.

![issueajsevillano](https://user-images.githubusercontent.com/44264807/78942951-0afc4780-7abb-11ea-832f-ce87657f6114.gif)

**Comment by ajsevillano** [comment]
This solution works perfectly!

Thank you for your help, I really appreciate your help on this Issue! 👍 

¡Un saludo!
